name: Google Cloud Run

on:
  workflow_dispatch

env:
  IMG_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1.6.0
        
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Build and push Next.js
          uses: docker/build-push-action@v2.9.0
          with:
            context: .
            push: true
            tags: ${{ env.IMG_NAME }}
            secrets: |
              "dotenv=${{ secrets.DOTENV }}"

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region asia-southeast1 --port=3000 --platform managed
